"""empty message

Revision ID: 043dad0ab6de
Revises: 
Create Date: 2018-07-28 19:44:26.673473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043dad0ab6de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('menu_type', sa.Enum('customized', 'general'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('taste_level', sa.Enum('mild', 'standard', 'strong'), nullable=True),
    sa.Column('water_level', sa.Enum('long', 'standard', 'small'), nullable=True),
    sa.Column('foam_level', sa.Enum('none', 'standard', 'thick'), nullable=True),
    sa.Column('grind_size', sa.Enum('fine', 'medium', 'coarse'), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.Column('customized_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_model',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('counts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('menu_id', 'order_id')
    )
    op.create_table('serial_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serial_number')
    op.drop_table('association_model')
    op.drop_table('order')
    op.drop_table('menu')
    op.drop_table('user')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
