"""empty message

Revision ID: 178695a29dca
Revises: e85fc3effb6c
Create Date: 2018-09-19 22:57:21.762147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178695a29dca'
down_revision = 'e85fc3effb6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_obsolete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'is_obsolete')
    # ### end Alembic commands ###
