"""empty message

Revision ID: 2cb29e48a953
Revises: 8bd1798ce4a9
Create Date: 2018-08-20 21:21:35.198479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb29e48a953'
down_revision = '8bd1798ce4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=False))
    op.add_column('user', sa.Column('gender', sa.Enum('none', 'male', 'female'), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
