"""empty message

Revision ID: 8bd1798ce4a9
Revises: 043dad0ab6de
Create Date: 2018-08-04 23:25:43.736013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd1798ce4a9'
down_revision = '043dad0ab6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial_number', sa.Column('menu_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'serial_number', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serial_number', type_='foreignkey')
    op.drop_column('serial_number', 'menu_id')
    # ### end Alembic commands ###
