"""empty message

Revision ID: e85fc3effb6c
Revises: 2cb29e48a953
Create Date: 2018-08-25 19:16:12.911198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e85fc3effb6c'
down_revision = '2cb29e48a953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=20),
               nullable=False)
    op.alter_column('user', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
